#ifndef FCOPERATORSINTERFACEAPI_H
#define FCOPERATORSINTERFACEAPI_H


#include <QtCore/QtGlobal>
#include "FCGlobals.h"

#if defined(FCOPERATORSINTERFACE_BUILDLIB)
#define FCOPERATORSINTERFACE_API Q_DECL_EXPORT
#else
#ifdef Q_CC_MSVC
#define FCOPERATORSINTERFACE_API Q_DECL_IMPORT
#else
#define FCOPERATORSINTERFACE_API Q_DECL_IMPORT
#endif
#endif

#endif // FCOPERATORSINTERFACEAPI_H
