#ifndef FCMESSAGEHANDLERAPI_H
#define FCMESSAGEHANDLERAPI_H
#include <QtCore/QtGlobal>
#include "FCGlobals.h"

#if defined(FCMESSAGEHANDLER_BUILDLIB)
#define FCMESSAGEHANDLER_API	Q_DECL_EXPORT
#else
#define FCMESSAGEHANDLER_API	Q_DECL_IMPORT
#endif

#endif // FCMESSAGEHANDLERAPI_H
