#ifndef FCACTIONOPERATORSAPI_H
#define FCACTIONOPERATORSAPI_H

#include <QtCore/QtGlobal>
#include "FCGlobals.h"

#if defined(FCACTIONOPERATORS_BUILDLIB)
#define FCACTIONOPERATORS_API Q_DECL_EXPORT
#else
#ifdef Q_CC_MSVC
#define FCACTIONOPERATORS_API Q_DECL_IMPORT
#else
#define FCACTIONOPERATORS_API Q_DECL_IMPORT
#endif
#endif

#endif // FCACTIONOPERATORSAPI_H
