#ifndef FCGEOMETRYMODELAPI_H
#define FCGEOMETRYMODELAPI_H
#include <QtCore/QtGlobal>
#include "FCGlobals.h"

#if defined(FCGEOMETYRMODEL_BUILDLIB)
#define FCGEOMETRYMODEL_API Q_DECL_EXPORT
#else
#define FCGEOMETRYMODEL_API Q_DECL_IMPORT
#endif
#endif // FCGEOMETRYMODELAPI_H
