#ifndef FCRENDERWINDOWVTKAPI_H
#define FCRENDERWINDOWVTKAPI_H

#include <QtCore/QtGlobal>
#include "FCGlobals.h"

#if defined(FCRENDERWINDOWVTK_BUILDLIB)
#define FCRENDERWINDOWVTK_API Q_DECL_EXPORT
#else
#ifdef Q_CC_MSVC
#define FCRENDERWINDOWVTK_API Q_DECL_IMPORT
#else
#define FCRENDERWINDOWVTK_API Q_DECL_IMPORT
#endif
#endif

#endif // FCRENDERWINDOWVTKAPI_H
