#ifndef FCGEOMETRYMODELCREATORAPI_H
#define FCGEOMETRYMODELCREATORAPI_H
#include <QtCore/QtGlobal>
#include "FCGlobals.h"

#if defined(FCGEOMETYRMODELCREATOR_BUILDLIB)
#define FCGEOMETRYMODELCREATOR_API Q_DECL_EXPORT
#else
#define FCGEOMETRYMODELCREATOR_API Q_DECL_IMPORT
#endif
#endif // FCGEOMETRYMODELCREATORAPI_H
